server:
  port: 8080

swagger.config:
  title: Prudential Car Service
  desc: Prudential Car Service API Document
  version: 1.0.0
  enable: true

spring:
  servlet:
    multipart:
      max-file-size: 20MB #单个上传文件大小
      max-request-size: 200MB #单个请求总上传文件大小

  jackson:
    default-property-inclusion: non_null #忽略null属性
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8" #设置时区，否则将数据库中的时间拿出来会少8小时
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rental?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useAffectedRows=true
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20

#mybatis配置
mybatis:
  type-aliases-package: com.prudential.car.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  logImpl:
